services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smsol_studio_network
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smsolstudio_app
    restart: unless-stopped

    volumes:
      - .:/var/www/html
      - app_var:/var/www/html/var
      
    networks:
      - smsol_studio_network
    depends_on:
      - mysql
    environment:
      APP_ENV: prod
        APP_SECRET: ${APP_SECRET:-ChangeMeInProduction}
        DATABASE_URL: "mysql://smsol_studio_user:she_12345@mysql:3306/gsmsol_studio_db?serverVersion=8.0&charset=utf8mb4"

    ports:
      - "8000:80"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - smsol_studio_network
volumes:
  mysql_data:

networks:
  smsol_studio_network:

parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'